### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Arshit01** [igorquintaes/DelugeRPG-Moveset-Calculator#1]
When I am building the code with visual studio 2010 with batch build there are so many errors in AttackDatabase.cs, few in AttackAnalyser.cs and least like 5 or 10 in Program.cs(about `$` on line 153).
What is the solution? Is it because of my visual studio version?

**Comment by igorquintaes** [comment]
you're probably using an outdated c# version. `$` is from C# 6. It was released at July 2015, with Visual Studio 2015.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

**Comment by Arshit01** [comment]
> you're probably using an outdated c# version. `$` is from C# 6. It was released at July 2015, with Visual Studio 2015.
> 
> https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

Thank you for reply i will try updating my C# version.

**Comment by Arshit01** [comment]
Hi bro, I have updated the attack database for some new attack in the game and I have the code + build if you say I will submit to you.

**Comment by igorquintaes** [comment]
> Hi bro, I have updated the attack database for some new attack in the game and I have the code + build if you say I will submit to you.

Hey, @Arshit01. You can fork this project, add your code and submit a pull request :)
Would be nice to learn git and open source, monstly projects accept changes this way.

Example: https://jarv.is/notes/how-to-pull-request-fork-github/
